apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: name-of-frontendconfig
  namespace: istio-system
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
